go get github.com/Sirupsen/logrus
go get github.com/grpc-ecosystem/go-grpc-prometheus
go get github.com/mwitkow/go-conntrack
go get github.com/mwitkow/go-conntrack/connhelpers
go get github.com/mwitkow/go-grpc-middleware
go get github.com/mwitkow/go-grpc-middleware/logging/logrus
go get github.com/mwitkow/grpc-proxy/proxy
go get github.com/prometheus/client_golang/prometheus/promhttp
go get github.com/spf13/pflag
go get github.com/rs/cors
go get github.com/golang/protobuf/protoc-gen-go
