/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.grpc.experimental.browser_compat.BrowserTerminator', null, global);
goog.exportSymbol('proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.experimental.browser_compat.BrowserTerminator = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.grpc.experimental.browser_compat.BrowserTerminator.repeatedFields_, null);
};
goog.inherits(proto.grpc.experimental.browser_compat.BrowserTerminator, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc.experimental.browser_compat.BrowserTerminator.displayName = 'proto.grpc.experimental.browser_compat.BrowserTerminator';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.experimental.browser_compat.BrowserTerminator.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.experimental.browser_compat.BrowserTerminator} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.toObject = function(includeInstance, msg) {
  var f, obj = {
    statusCode: msg.getStatusCode(),
    statusDesc: msg.getStatusDesc(),
    trailerList: jspb.Message.toObjectList(msg.getTrailerList(),
    proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc.experimental.browser_compat.BrowserTerminator}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc.experimental.browser_compat.BrowserTerminator;
  return proto.grpc.experimental.browser_compat.BrowserTerminator.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc.experimental.browser_compat.BrowserTerminator} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc.experimental.browser_compat.BrowserTerminator}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatusCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatusDesc(value);
      break;
    case 3:
      var value = new proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader;
      reader.readMessage(value,proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.deserializeBinaryFromReader);
      msg.getTrailerList().push(value);
      msg.setTrailerList(msg.getTrailerList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.grpc.experimental.browser_compat.BrowserTerminator} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getStatusCode();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = this.getStatusDesc();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getTrailerList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.grpc.experimental.browser_compat.BrowserTerminator} The clone.
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.prototype.cloneMessage = function() {
  return /** @type {!proto.grpc.experimental.browser_compat.BrowserTerminator} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 status_code = 1;
 * @return {number}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.prototype.getStatusCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.grpc.experimental.browser_compat.BrowserTerminator.prototype.setStatusCode = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string status_desc = 2;
 * @return {string}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.prototype.getStatusDesc = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.grpc.experimental.browser_compat.BrowserTerminator.prototype.setStatusDesc = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated TrailingHeader trailer = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader>}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.prototype.getTrailerList = function() {
  return /** @type{!Array.<!proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader, 3));
};


/** @param {Array.<!proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader>} value  */
proto.grpc.experimental.browser_compat.BrowserTerminator.prototype.setTrailerList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


proto.grpc.experimental.browser_compat.BrowserTerminator.prototype.clearTrailerList = function() {
  this.setTrailerList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.displayName = 'proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader} msg The msg instance to transform.
 * @return {!Object}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: msg.getName(),
    value: msg.getValue()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader;
  return proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader} The clone.
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.prototype.cloneMessage = function() {
  return /** @type {!proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.grpc.experimental.browser_compat.BrowserTerminator.TrailingHeader.prototype.setValue = function(value) {
  jspb.Message.setField(this, 2, value);
};


goog.object.extend(exports, proto.grpc.experimental.browser_compat);
