/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var nested_somenested_pb = require('./nested/somenested_pb.js');
goog.exportSymbol('proto.mwitkow.proto.Empty', null, global);
goog.exportSymbol('proto.mwitkow.proto.PingRequest', null, global);
goog.exportSymbol('proto.mwitkow.proto.PingResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mwitkow.testproto.Empty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mwitkow.testproto.Empty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mwitkow.testproto.Empty.displayName = 'proto.mwitkow.proto.Empty';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mwitkow.testproto.Empty.prototype.toObject = function(opt_includeInstance) {
  return proto.mwitkow.testproto.Empty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mwitkow.testproto.Empty} msg The msg instance to transform.
 * @return {!Object}
 */
proto.mwitkow.testproto.Empty.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mwitkow.testproto.Empty}
 */
proto.mwitkow.testproto.Empty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mwitkow.testproto.Empty;
  return proto.mwitkow.testproto.Empty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mwitkow.testproto.Empty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mwitkow.testproto.Empty}
 */
proto.mwitkow.testproto.Empty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.mwitkow.testproto.Empty} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.mwitkow.testproto.Empty.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mwitkow.testproto.Empty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.mwitkow.testproto.Empty.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.mwitkow.testproto.Empty} The clone.
 */
proto.mwitkow.testproto.Empty.prototype.cloneMessage = function() {
  return /** @type {!proto.mwitkow.testproto.Empty} */ (jspb.Message.cloneMessage(this));
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mwitkow.testproto.PingRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mwitkow.testproto.PingRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mwitkow.testproto.PingRequest.displayName = 'proto.mwitkow.proto.PingRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mwitkow.testproto.PingRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.mwitkow.testproto.PingRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mwitkow.testproto.PingRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.mwitkow.testproto.PingRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: msg.getValue(),
    sleepTimeMs: msg.getSleepTimeMs(),
    errorCodeReturned: msg.getErrorCodeReturned()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mwitkow.testproto.PingRequest}
 */
proto.mwitkow.testproto.PingRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mwitkow.testproto.PingRequest;
  return proto.mwitkow.testproto.PingRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mwitkow.testproto.PingRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mwitkow.testproto.PingRequest}
 */
proto.mwitkow.testproto.PingRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSleepTimeMs(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setErrorCodeReturned(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.mwitkow.testproto.PingRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.mwitkow.testproto.PingRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mwitkow.testproto.PingRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.mwitkow.testproto.PingRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getValue();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getSleepTimeMs();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = this.getErrorCodeReturned();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.mwitkow.testproto.PingRequest} The clone.
 */
proto.mwitkow.testproto.PingRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.mwitkow.testproto.PingRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string value = 1;
 * @return {string}
 */
proto.mwitkow.testproto.PingRequest.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.mwitkow.testproto.PingRequest.prototype.setValue = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 sleep_time_ms = 2;
 * @return {number}
 */
proto.mwitkow.testproto.PingRequest.prototype.getSleepTimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.mwitkow.testproto.PingRequest.prototype.setSleepTimeMs = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint32 error_code_returned = 3;
 * @return {number}
 */
proto.mwitkow.testproto.PingRequest.prototype.getErrorCodeReturned = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.mwitkow.testproto.PingRequest.prototype.setErrorCodeReturned = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mwitkow.testproto.PingResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mwitkow.testproto.PingResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.mwitkow.testproto.PingResponse.displayName = 'proto.mwitkow.proto.PingResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mwitkow.testproto.PingResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.mwitkow.testproto.PingResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mwitkow.testproto.PingResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.mwitkow.testproto.PingResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: msg.getValue(),
    counter: msg.getCounter(),
    something: (f = msg.getSomething()) && nested_somenested_pb.SomeMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mwitkow.testproto.PingResponse}
 */
proto.mwitkow.testproto.PingResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mwitkow.testproto.PingResponse;
  return proto.mwitkow.testproto.PingResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mwitkow.testproto.PingResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mwitkow.testproto.PingResponse}
 */
proto.mwitkow.testproto.PingResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCounter(value);
      break;
    case 3:
      var value = new nested_somenested_pb.SomeMessage;
      reader.readMessage(value,nested_somenested_pb.SomeMessage.deserializeBinaryFromReader);
      msg.setSomething(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.mwitkow.testproto.PingResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.mwitkow.testproto.PingResponse.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mwitkow.testproto.PingResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.mwitkow.testproto.PingResponse.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getValue();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getCounter();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = this.getSomething();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      nested_somenested_pb.SomeMessage.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.mwitkow.testproto.PingResponse} The clone.
 */
proto.mwitkow.testproto.PingResponse.prototype.cloneMessage = function() {
  return /** @type {!proto.mwitkow.testproto.PingResponse} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string Value = 1;
 * @return {string}
 */
proto.mwitkow.testproto.PingResponse.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.mwitkow.testproto.PingResponse.prototype.setValue = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 counter = 2;
 * @return {number}
 */
proto.mwitkow.testproto.PingResponse.prototype.getCounter = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.mwitkow.testproto.PingResponse.prototype.setCounter = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional nested.SomeMessage something = 3;
 * @return {proto.mwitkow.testproto.nested.SomeMessage}
 */
proto.mwitkow.testproto.PingResponse.prototype.getSomething = function() {
  return /** @type{proto.mwitkow.testproto.nested.SomeMessage} */ (
    jspb.Message.getWrapperField(this, nested_somenested_pb.SomeMessage, 3));
};


/** @param {proto.mwitkow.testproto.nested.SomeMessage|undefined} value  */
proto.mwitkow.testproto.PingResponse.prototype.setSomething = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.mwitkow.testproto.PingResponse.prototype.clearSomething = function() {
  this.setSomething(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.mwitkow.testproto.PingResponse.prototype.hasSomething = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.mwitkow.testproto);
